### ISSUE TITLE
Can userResponsible() of Revision use relationship (belongsTo)?

### ISSUE THREAD

**Issue by anggras** [VentureCraft/revisionable#104]
To reduce number of queries especially in listing history, it'll be better to use relationship to the user model instead of doing another query with find(). By using relationship, we'll be able to use eager loading (http://laravel.com/docs/eloquent#eager-loading).

**Comment by runonce86** [comment]
I know this is very old but what was the conclusion? The user model can be known by Revisionable as @anggras already shown. It would be useful to have `userResponsible()` defined as a relationship, this would enable eager loading the user instance for example.
