### ISSUE TITLE
[Question/Suggestion] Using Revisionable with approvals

### ISSUE THREAD

**Issue by torrobinson** [VentureCraft/revisionable#123]
Hello, 

I'm building my first Laravel application and Revisionable looks to fill a need I had. However, I am looking to store most updates to revisionable models into a custom "approvals" table, where I will keep track of requested field changes and who requested them. Upon approval, I'll actually be making those updates to the models.

So on approval, I assume Revisionable will store the userResponsible as the current user (the approver). How would you suggest I modify Revisionable so that I can specify a custom "userResponsible" (in this case, the user who requested a change, not who is approving it)?

Being new to Laravel, I'm unsure if there's a way I could perhaps extend a model's "Save" method to allow a custom userResponsible to be passed in and caught by the event listeners that Revisionable sets up... is this possible and is this the way to do it?

Any tips appreciated, thanks!

**Comment by torrobinson** [comment]
I ended up not using Revisionable - I extended ```Eloquent``` and overrode the ```save()```, ```update()``` and ```insert()``` methods to handle saving the changed (dirty columns) to a ```revision``` and ```revisionBatch``` table. Actually could have done this as Trait...

That way our approvers can view a bulk list of attempted changes down to every field and approve/deny them. Approving a batch performs the initially intended SQL statements in order.

**Comment by rjvim** [comment]
@torrobinson Hi, Is there a package/code you shared anywhere which has the above implementation? Thanks.

**Comment by ellej16** [comment]
Seconding @rjvim 's inquiry, perhaps create a PR for  (or have Revisionable work with) the feature you implemented? Sounds like a mighty good feature to have @torrobinson .

**Comment by torrobinson** [comment]
Hey @rajivseelam and @ellej16 - sorry but this was years ago, so I don't recall the specifics, but it wasn't something really in a state clean enough to PR in or release to the world. In fact the project was cancelled a few months later... :(

However, generally I right before what I would define as a "batch" of changes (scope up to you), I'd create a new `RevisionBatch` row in my database, take the resulting `batch_id`, and would pass it to all my `->save()`, `->insert()`, and `->update()` methods I extended in custom class extension of `Eloquent`. Inside, rather than saving to their respective models, they'd save something like this to the `Revision` model:

```
+----------+----------------+-----------+-----------------+---------------+-----------+-----------+
| batch_id |     table      | table_key | revision_column | revision_type | old_value | new_value |
+----------+----------------+-----------+-----------------+---------------+-----------+-----------+
|      123 | user_profiles  |         1 | first_name      | update        | Bobby     | Bob       |
|      456 | friend_request |           | from            | insert        |           | user_1    |
|      456 | friend_request |           | to              | insert        |           | user_2    |
|      789 | friend_request |         4 |                 | delete        |           |           |
+----------+----------------+-----------+-----------------+---------------+-----------+-----------+
``` 

So essentially I'd call the normal insert/update/deletes on models, but if that model extended `Revisionable` or whatever I called my `Eloquent` extension, then the changes were redirected and built into instructions like in the table above.

When a `Revision Batch` was approved, then "inserts" had all their columns inserted, updates would update specific columns, and deletes would just delete the entire row.

---

It actually did end up working, but it felt very hacky and I wish there was something out there that did it for me - like I said the project was also cancelled and so I never saw how it performed out in the wild, nor did it stand up to much testing or scrutiny. 

If you want, I can see if I still have the source code when I get home and look for snippets of it?

**Comment by ellej16** [comment]
@torrobinson - sure! the idea makes sense (approving a change before applying said change) so we'd love to see the snippets if you may.

Also, is the `table_key` column on the `revisions` table refer to the `id` of the specific record that is to be updated?  if so, why are there two rows which have blank/null values? does having it blank mean anything? Genuinely curious.

Thanks!

**Comment by torrobinson** [comment]
Hey @ellej16,

Those weren't my exact column names, but yes you'd have something refer to the key within the table you're affecting - they're blank when `revision_type` is `insert` because on an insert, you wouldn't have or know the PK it's going to be assigned yet and so there's not much you can do with that column

**Comment by dakshhmehta** [comment]
I have done this similar type of thing in past and working good. Opened a merge request, meanwhile maybe have a look at modified trait and you should be good to go.

Feel free to ask anything in implementation, will be happy to help
