### ISSUE TITLE
One of my Models doesn't make any History of changes?

### ISSUE THREAD

**Issue by mansouralex** [VentureCraft/revisionable#124]
One of my Models doesn't make any History of changes while I have used the package same as my other models.

Here is how my Model looks, If you notice any typo errors or  something missing please let me know what it is. Thanks

    <?php

    use Illuminate\Database\Eloquent\SoftDeletingTrait;

    class ClientService extends Eloquent
    {
        use \Venturecraft\Revisionable\RevisionableTrait;
        use \Venturecraft\Revisionable\RevisionOnCreateTrait;
        use SoftDeletingTrait;
    
        public $timestamps = false;
    
        protected $dates = ['deleted_at'];
    
     //   protected $revisionEnabled = true;
    
        protected $table = 'services';

        protected $keepRevisionOf = array(
            'name_en',
            'name_ar',
            'service_type',
            'service_code',
            'deleted_at',
            'is_deleted'
        );
    
        protected $fillable = array('name_en', 'name_ar','service_type','service_code', 'is_deleted');
    
    }

**Comment by Bolandish** [comment]
I have a similar problem. 
I following your post :+1:

**Comment by rorymcdaniel** [comment]
I've got the same problem. I'm using this on two models, one keeps the revision, the other doesn't. Mine are both set up just like both of yours, but I'm not using the SoftDeletingTrait.

Any ideas?

**Comment by rorymcdaniel** [comment]
So I found the problem with mine, posting it here in case it helps anyone else.

The only difference between the two models was that the one that was not working had an observer defined. I essentially copied the observer portion from RevisionableTrait.php into the corresponding methods of my observer, and now it works. There's got to be a better way, but for now, I'm happy because it works.

**Comment by astierler** [comment]
@rorymcdaniel just chiming in to close this out for now..

Laravel 5.x fixes this by using the `bootRevisionableTrait` function. For backward compatibility, the static function `boot` still exists in RevisionableTrait.

If you are on Laravel 4.x and have your own overridden `boot()` function (or another trait that may do so), in boot just make a call to `self::bootRevisionableTrait()`

I will try to update the docs for the 4.x compatibility version for those running into this.
