### ISSUE TITLE
L5 ?

### ISSUE THREAD

**Issue by andregeges** [VentureCraft/revisionable#125]
Hi, how to use this package on L5 ?

**Comment by duellsy** [comment]
As the docs state, Revisionable V1 is for Laravel 4.

Work on a laravel 5 version has not begun.

**Comment by itsazzad** [comment]
When can we have a version for L5?

**Comment by duellsy** [comment]
Unsure, I need to find the time to work on this. However, this pull request allows it to he installed, it's just not officially supported: 
https://github.com/VentureCraft/revisionable/pull/105
