### ISSUE TITLE
Limit for Track History

### ISSUE THREAD

**Issue by arvind132** [VentureCraft/revisionable#136]
Hi, i need a support that, is there any possibility for setting a limit to stop the revision history for a modal. (if the limit cross the package should not have to keep the history for the modal). please help me,

**Comment by duellsy** [comment]
Hi, this isn't supported by the package I'm afraid. 
Happy to accept a pull request for it.

**Comment by sniper7kills** [comment]
@arvind132 I'll try to update my existing pull request to include this feature. If you want to code it yourself; it shouldn't be difficult just a matter of overriding the postSave function in Revisionable trait to check how many revisions the model already has; and not updating it if it is above the threshold you set.

**Comment by sniper7kills** [comment]
Please see pull request #135 I have added this feature request into my pull.

**Comment by arvind132** [comment]
Thanks for the code, really its so useful.
