### ISSUE TITLE
Not able to get the foreign value relations for a revision

### ISSUE THREAD

**Issue by BlazeNikhilesh** [VentureCraft/revisionable#140]
So, I have a model Tickets. I want to keep revision of assigned_to and stage_id. I read that I can display String instead of ID using this function 
 public function identifiableName()
    {
        return $this->getKey();
    }
But, I am not able to override this in my Tickets model.

**Comment by duellsy** [comment]
This would belong in your Stage model, so when you are getting the stage from the history of the ticket, it will return something other than the stage_id, perhaps your stage name
