### ISSUE TITLE
Birthday value in history

### ISSUE THREAD

**Issue by divdax** [VentureCraft/revisionable#158]
Hey,

i have a birthday field from type date (YYYY-MM-DD) and it's also defined as a date in my model.
Now if i save the model the birthday has changed like this:

```
birthday changed from 1999-09-04 to 1999-09-04 12:07:38
```

**Comment by ecmattos** [comment]
Hi, divdax! 
Are you still with this problem ?

**Comment by divdax** [comment]
I fixed the problem with laravels setAttribute like so:
```
public function setReleasedateAttribute($value)
{
    $this->attributes['releasedate'] = Carbon::parse($value)->format('Y-m-d');
}
```
