### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by omar-faruk-sust** [VentureCraft/revisionable#159]
i am trying to use this package but it's not working, can you tell me what's wrong with my code?
```php
<?php 
namespace App;
use Illuminate\Database\Eloquent\Model;
class Books extends Model {
	use \Venturecraft\Revisionable\RevisionableTrait;

	public static function boot()
	{
		parent::boot();
	}
	protected $revisionEnabled = true;
	protected $table = 'books';
	protected $fillable  = ['isbn','title','author','publisher','language'];
}
```

anyone can provide me an working example?

**Comment by divdax** [comment]
I think you have to remove the boot() method.

**Comment by omar-faruk-sust** [comment]
hi @divdax i remove the boot method but it's not working. i want to mention that i am using another package for another purpose. in that package there is a boot method.

**Comment by ecmattos** [comment]
try this:

<?php 
namespace App;
use Illuminate\Database\Eloquent\Model;
use \Venturecraft\Revisionable\RevisionableTrait;

class Books extends Model {

    public static function boot()
    {
        parent::boot();
    }
    protected $revisionEnabled = true;
    protected $table = 'books';
    protected $fillable  = ['isbn','title','author','publisher','language'];
}

**Comment by astierler** [comment]
I'm guessing this got resolved? If not, which version of Laravel are you on?

If you are on 4.x and need to overwrite the boot function, you can always include this inside of your custom `boot()` to call the Revisionable boot:

```php
this::bootRevisionableTrait();
```
