### ISSUE TITLE
RevisionableTrait conflicts with EntrustUserTrait

### ISSUE THREAD

**Issue by sumityadav** [VentureCraft/revisionable#175]
I am using Laravel Framework version 5.1.20 (LTS)

I am using EntrustUserTrait and RevisionableTrait where the boot method is present in both traits and doesn't load because of the conflicts. Is there a way to get them working together?

Thanks

**Comment by alexhouse** [comment]
When you use the traits at the top of your model, you can pick which method to use:

```use RevisionableTrait, EntrustUserTrait {
    EntrustUserTrait::boot insteadof RevisionableTrait;
}```

Laravel 5.1 should use `Revisionable`'s `bootRevisionableTrait` method instead of boot
