### ISSUE TITLE
Saving multiple values not working.

### ISSUE THREAD

**Issue by AdrianB93** [VentureCraft/revisionable#176]
Revisionable is only logging "expires_at" when saving multiple values like so:

    $contract = Contract::find(1);
    $contract->is_active = true;
    $contract->status = 'pending';
    $contract->expires_at = Carbon::now()->addDays(5);
    $contract->save();

I need the other values to be logged in the revisions table too.

I'm using Postgres 9.4.4 and dumping `$this->dirtyData` in `RevisionableTrait@preSave` only contains "expires_at"

    array(1) { ["expires_at"]=> object(Carbon\Carbon)#367 (3) { ["date"]=> string(26) "2015-11-08 10:14:22.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(16) "Australia/Sydney" } }

**Comment by AdrianB93** [comment]
Sorry, a `artisan clear-compiled` and `artisan optimize` fixed the issue.

**Comment by duellsy** [comment]
:) Awesome.
