### ISSUE TITLE
Package migration doesnt work L5.1.24

### ISSUE THREAD

**Issue by ricklwd** [VentureCraft/revisionable#181]
> Finally, you'll also need to run migration on the package
> php artisan migrate --package=venturecraft/revisionable

This wil throw an error: **exception 'RuntimeException' with message 'The "--package" option does not exist**. Apparantly the --package switch is not supported anymore as of L5.1.24

Please change documentation from:
> Finally, you'll also need to run migration on the package
> php artisan migrate --package=venturecraft/revisionable

To:

> Finally, you'll also need to run migration on the package
>php artisan migrate --path=vendor/venturecraft/revisionable/src/migrations

As this will solve this problem.

Regards, Rick

**Comment by Eldair** [comment]
+1

**Comment by bernex** [comment]
Try this:

```
php artisan migrate --path=vendor/venturecraft/revisionable/src/migrations
```

--package - removed (

**Comment by victor-ponamariov** [comment]
It'd be a good idea to update installation docs. 
`php artisan migrate --path=vendor/venturecraft/revisionable/src/migrations` worked fine, just in docs it's still --package

Thanks for your package!

**Comment by juanvillegas** [comment]
I think the --package is for older Laravel versions (like v4)

**Comment by astierler** [comment]
Documentation updated for next release for both Laravel major versions

**Comment by KharChin** [comment]
I write this" php artisan make:model Post --migration"
it show this
 [RuntimeException]   
The "--migration" option does not exist.
what is wrong? someone plz help me.

**Comment by astierler** [comment]
@KharChin not really related to this project, but which Laravel are you running?

Try checking `php artisan make:model --help` to see if the migration option is even there.  It may not have been added until a later version if you are on an older one. (I ran the same command with no issue).

**Comment by KharChin** [comment]
Dear astierler, thank you. I got this. I use laravel 5.0. > php artisan make:model Post . I write this. It in now ok.
