### ISSUE TITLE
Cant create list of all changes

### ISSUE THREAD

**Issue by tdolph** [VentureCraft/revisionable#184]
How can i get the list of all updates?

I am trying to make an activity log for my website that displays updates on articles, posts, users and all that stuff. But, i cant figure out how to get all revisions, not just for single model or user.

**Comment by duellsy** [comment]
You can load them just like you would any other model, i.e.,

```
$revisions = Revision::all();
```

**Comment by grex22** [comment]
I get "Class Revision not found" -- Am I missing something?
