### ISSUE TITLE
Don't log if nothing is wrong

### ISSUE THREAD

**Issue by philippejadin** [VentureCraft/revisionable#186]
Here : https://github.com/VentureCraft/revisionable/blob/master/src/Venturecraft/Revisionable/Revision.php#L175

This line fills the log with an "info" that is probably not useful. 
I get this for each display of history : 

production.INFO: Revisionable: exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::getRevisionUnknownString()' in /[...]/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2071

This might fill the log quickly. Or is it the purpose of log@ info level?

**Comment by philippejadin** [comment]
Or maybe, it is because a related model has not the revisionable trait. In this case I'd consider this as a bug. 
Anyone has insight on this?

**Comment by roryatbrightoak** [comment]
I realize this is an old issue, but since it's still marked as open...

I have exactly the same question. Is this a problem that I need to address in the code in some way? Or do I simply need to change my overall log level setting?

**Comment by Gummibeer** [comment]
It seems that it tries to call the method on a model that doesn't use the trait.
So it could be that you can solve it by using the trait in the related model.

**Comment by philippejadin** [comment]
...which probably means it's a bug :-) But unfortunately I have no idea how to fix it

**Comment by Gummibeer** [comment]
A simple `method_exists()` should solve it.
