### ISSUE TITLE
Fields type DATE - new_value with time (00:00:00)

### ISSUE THREAD

**Issue by ecmattos** [VentureCraft/revisionable#187]
Each registry editing , the fields of type DATE are changed unwittingly adding to new_value field in the table revisionable with hours, minutes and seconds ( 07/12/2015 00:00:00 ) . How do I make the hours , minutes and seconds are disregarded ( 07/12/2015 ) ?

**Comment by duellsy** [comment]
Perhaps try making sure that the date you are saving is the date only, with no time on it?

**Comment by ecmattos** [comment]
I am using datepicker in my fields type of a Date. I realize the conversion the format from d/m/Y to Y-m-d assistance of Carbon. I apply to dd ($date_start) to check if there is no information on the hour, minutes and seconds , really, I just show up the only date.

**Comment by ecmattos** [comment]
The issue #158 is the same problem.

**Comment by ecmattos** [comment]
My controller:
$input = $request->all();

if($input['date_fundacao'])
{
  $input['date_fundacao'] = \DateTime::createFromFormat('d/m/Y', $input['date_fundacao']);
  $input['date_fundacao'] = $input['date_fundacao']->format('Y-m-d');
}
else
{
  $input['date_fundacao'] = null;
}

**Comment by ecmattos** [comment]
????

**Comment by ecmattos** [comment]
?????????????????
