### ISSUE TITLE
getUserId

### ISSUE THREAD

**Issue by roshangautam** [VentureCraft/revisionable#198]
Function getUserId clashes with the same function name in Sentinel User Model. Hence if we try to track revisions of Sentinel User Model by adding RevisionableTrait the getUserId function returns null while trying to login because of the following line:

<code>return ($class::check()) ? $class::getUser()->id : null;</code>

Renaming the function to getSystemUserId or something else fixes the problem.

**Comment by astierler** [comment]
#199 has been merged. I've also applied it to the non-trait version as well for consistency.

**Comment by roshangautam** [comment]
Wonderful. Thanks @astierler
