### ISSUE TITLE
Strange unique key error

### ISSUE THREAD

**Issue by ryanwinchester** [VentureCraft/revisionable#206]
I've been getting this error type lately but I don't understand why.

```
"SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "revisions_pkey"

DETAIL: Key (id)=(4) already exists. (
    SQL: insert into "revisions" (
        "created_at", "key", "new_value", "old_value", "revisionable_id", "revisionable_type", "updated_at", "user_id"
    ) values (
        2016-02-16 23:11:19, is_published, 0, 1, 33, Flashtag\Data\Post, 2016-02-16 23:11:19, 2
    )
)"
```

**Comment by ryanwinchester** [comment]
Ah well, I truncated the revisions table and it works fine now.

**Comment by ceejayoz** [comment]
For the record (and anyone searching and finding this like I did), I was able to resolve this by running the query `SELECT setval('revisions_id_seq', max(id)) FROM revisions')` to reset the sequence on the `revisions` table's `id` column.
