### ISSUE TITLE
revisionHistory with limit

### ISSUE THREAD

**Issue by cse031sust02** [VentureCraft/revisionable#214]
Can i get revision history with 10 data or so ?
something like $user->revisionHistory(10)?

**Comment by cargie** [comment]
no since its using eloquent relationship but you can make a function that would take revision history with limit parameter.

**Comment by astierler** [comment]
@cse031sust02 you can take advantage of the fact `revisionHistory()` is a morphMany relationship.

Use code similar to this to get a `Collection` back.
```php
$revisions = $model->revisionHistory()->take(5)->get();
```

Note: you must use `revisionHistory` as a function.  If you don't care about performance or the size of your query, you can just do `$revisions = $model->revisionHistory->take(5);`
