### ISSUE TITLE
Instructions not working.

### ISSUE THREAD

**Issue by ArtisanTinkerer** [VentureCraft/revisionable#217]
This how the instructions says to use:

```
namespace MyApp\Models;

class Article extends Eloquent {
    use \Venturecraft\Revisionable\RevisionableTrait;

    public static function boot()
    {
        parent::boot();
    }
}

```

When I look in in my models, they extend Model, not Eloquent.

When I try this code:

```
class Record extends Model

{
    use Venturecraft\Revisionable\RevisionableTrait;

```

I get: 
 Fatal error: Trait 'App\Venturecraft\Revisionable\RevisionableTrait' not found in /var/www/html/selection/app/Record.php on line 13

What am I doing wrong?

Mick

**Comment by onbjerg** [comment]
You're missing a ``\`` in your code.

**Comment by ArtisanTinkerer** [comment]
Here?

```
use \Venturecraft\Revisionable\RevisionableTrait;
```

I get the same error.

**Comment by onbjerg** [comment]
Try to do ``composer dump-autoload``

**Comment by ArtisanTinkerer** [comment]
Got further now.

Class 'Auth' not found in /var/www/html/selection/vendor/venturecraft/revisionable/src/Venturecraft/Revisionable/RevisionableTrait.php

**Comment by ArtisanTinkerer** [comment]
An this now:

Class 'DB' not found' in /var/www/html/selection/vendor/venturecraft/revisionable/src/Venturecraft/Revisionable/RevisionableTrait.php:260

```
\DB::table($revision->getTable())->insert($revisions);

```

**Comment by ArtisanTinkerer** [comment]
If I add:
```
 use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
```

Then swap the 

```
\DB::table($revision->getTable())->insert($revisions);
```

for:

```
DB::table($revision->getTable())->insert($revisions);

```

Why do I need to do this?

Mick

**Comment by onbjerg** [comment]
Seems a bit odd. Are your facades configured correctly?

**Comment by ArtisanTinkerer** [comment]
I assume so, I have not changed anything.

How can I check?

Should this work with 5.1?

**Comment by onbjerg** [comment]
It should, yes.

**Comment by ArtisanTinkerer** [comment]
What can I check then?

My understanding is that \DB should just work, because it references the root namespace.

**Comment by ArtisanTinkerer** [comment]
Working now, my app.php was corrupt.
