### ISSUE TITLE
Revisions on many-to-many relationships

### ISSUE THREAD

**Issue by bpfruin** [VentureCraft/revisionable#221]
I'm a new, inexperienced Laravel developer.  Is there a way to record revisions on many-to-many relationships?  For example, User and Role is M:N and I want to add or remove a Role from a user.  Is there a way for revisionable to record that?  If there's not, how would I go about doing that?  Should I add a record to the revisions table manually in the boot update method of the User model?

**Comment by duellsy** [comment]
Sorry, revisionable does not handle Many to Many relationship revisions. It's something that you'll need to manually manage and store outside of elevio.
