### ISSUE TITLE
Deleted Records

### ISSUE THREAD

**Issue by whfamily2006** [VentureCraft/revisionable#224]
Is this package record the delete record. e.g. who delete the record..??

**Comment by astierler** [comment]
@whfamily2006 yes, but you must be using Soft Deletes.  See https://github.com/VentureCraft/revisionable#storing-soft-deletes

**Comment by astierler** [comment]
@whfamily2006 FYI if you'd like to record hard deletes, I pasted an example at the ServiceProvider level here: https://github.com/VentureCraft/revisionable/issues/243#issuecomment-238738990

This works on delete() and forceDelete() calls
