### ISSUE TITLE
Get old value by specific date

### ISSUE THREAD

**Issue by ahtun** [VentureCraft/revisionable#227]
Hi, can I get old value by specific date.
For example: I have client table and invoice table (related to client table by 'client_id').
I create invoice with client data, after I changed client address, and created a second invoice.
If i do a request first invoice, i get a fresh address, but I need old.
Please help me. Thanks.

**Comment by duellsy** [comment]
Hi,

You'll need to get the list of revisions, and do a filter on that set to get the specific revision that you are after.
