### ISSUE TITLE
using trans and Lang with revisionFormattedFieldNames

### ISSUE THREAD

**Issue by illuminate3** [VentureCraft/revisionable#230]
```
	protected $revisionFormattedFieldNames = array(
		'last_move_date'			=> trans('kotoba::general.last_move_date'),
		'tech_status'				=> Lang::choice('kotoba::shop.tech_status', 1),
		'invoice'					=> Lang::choice('kotoba::shop.invoice', 1),
		'site'						=> Lang::choice('kotoba::cms.site', 1),
		'room'						=> Lang::choice('kotoba::hr.room', 1)
	);
```

As you can see, I'm trying to use the trans and Lang methods but I get the error:

```
syntax error, unexpected '(', expecting ')'
```

Any suggestions for a work around?

**Comment by astierler** [comment]
@illuminate3 you can't use functions as default values in expressions.

Best bet would be to leave `$revisionFormattedFieldNames = array();` and then in the `boot` method of your class (or whichever function initializes it) you can then set the formatted field names with those functions.

Hope this helps.
