### ISSUE TITLE
Revisionable seems to not work with my model

### ISSUE THREAD

**Issue by Kovah** [VentureCraft/revisionable#232]
I followed the instructions and added Revisionable to one of my models. After configuring it I tested updating an entry for the model but no revisions are created.
Migration was created and the database table exists.

This is how the model looks:
```php
namespace App\Models;
use Venturecraft\Revisionable\RevisionableTrait;

class Quote extends Model {
    use Rememberable, RevisionableTrait;

    protected $revisionEnabled = true;
    protected $revisionCleanup = true;
    protected $historyLimit = 50;
    protected $keepRevisionOf = array(
        'source', 'quote', ...
    );

    public static function boot() {
        parent::boot();
        static::addGlobalScope(new LanguageScope());
    }
    ...
```

This is the controller action to update the model entry from a form:
```php
Quote::where('id', $id)->update($request->except(['_method', '_token']));
```

* I already tried adding `self::bootRevisionableTrait();` to the boot() method but it's not working either.
* The model also has two `hasOne` relations but I don't think that they are blocking the revisions.
* I changed from `extends Model` to `extends Eloquent` but it's not working.

Am I missing something?

**Comment by astierler** [comment]
@Kovah when you use ->update directly onto Laravel's query builder, it essentially just makes a database call.

Try loading the quote, modifying and then calling save.

```
$quote = Quote::where('id', $id)->first();
// Your logic to update.
$quote->save();
```

**Comment by dtubby** [comment]
Also having the same issue. Unfortunately i've used the same logic all over my code and Revisionable hasn't stored any of the changes. 

having 3, 4+ lines of code instead of a quick one liner is messy to me.

**Comment by astierler** [comment]
@dtubby I understand why making the update (or delete) calls to the database directly is shorter time wise, and quicker - but that is unfortunately the trade-off you are stuck with.

That said, this isn't a limitation of Revisionable. In order for Laravel to even be aware of those updates, you need to load the records in first and call the appropriate Model functions.  No Eloquent events will be fired when making database calls directly.

**Comment by dtubby** [comment]
completely understand. thanks for the reply. At first its frustrating as suddenly i have 10 lines of code with a foreach to update the fields so it works with revisionable.

But looking at the code i can see why you would need to do it that way. Maybe it could be in the documentation? i feel like its something that would pop up and go unnoticed for alot of people. Surely im not the only one trying to simplify the code dramatically

**Comment by astierler** [comment]
@dtubby Agreed 100%. I will make sure this gets added to documentation. :+1:

**Comment by Kovah** [comment]
I will test this as soon as possible. Thanks for the hint, seems reasonable.
