### ISSUE TITLE
getting the deleted model with the revision

### ISSUE THREAD

**Issue by z1haze** [VentureCraft/revisionable#244]
Hi, I am trying to figure out how to fetch the trashed model when you are showing a deleted revision?

$revision->revisionable always seems to return null because I'm assuming the relationships are not being fetched with the trashed models.

Can this be done? thanks.

**Comment by astierler** [comment]
@z1haze please use http://stackoverflow.com/ for questions like this, as they aren't actual issues.

That being said, you'd have to pull it in on its own (not from the relationship method), ie. if your Revision is `$r`, then

```php
$deleted_model = (new $r->revisionable_type)->withTrashed()->find($r->revisionable_id);
```
