### ISSUE TITLE
Double record inserted in revisions

### ISSUE THREAD

**Issue by mistre83** [VentureCraft/revisionable#247]
I have create a simple model `Post` and extended `Revisionable` and used `RevisionableTrait`.

```
class Post extends Revisionable
{
    use RevisionableTrait;

    public $table = "posts";
    public $primaryKey = "id";

    public $timestamps = true;
    public $fillable = [
        'title'
    ];

    public static $rules = [

    ];
}

```

When i try to update a field, in `revisions` table i found two record, inserted at the same time.

**Comment by mnfgul** [comment]
@mistre83 I think you dont need to "extends" you model. Using trait will be enough.

**Comment by mistre83** [comment]
**What is the different from extend the model and use the trait ?**

I would like to use this plugin because in my project i need (for some model and some fields) a kind of "rollback".

Some fields in my model will be really critical, and i need a way to perform a rollback on it.

Reading the documentations, is what this plugins do (sure.. and much more!)

**Comment by mnfgul** [comment]
Extend is inheritance (paren/child) relationship. Trait is just copy/paste like code sharing. Using both creates this;
- When there is a change in Post model, trait creates a revision record using the Revision Model.
- Because Post is inherited from Revision, creating a revision will also triggers a change for Post model.

**Comment by mistre83** [comment]
Thanks a lot, i've already test it using just the extend and works well. I close the issue.

**Comment by morilog** [comment]
I have same problem, I'm using trait, but double records are inserted in database
