### ISSUE TITLE
Related Revisions

### ISSUE THREAD

**Issue by abebars** [VentureCraft/revisionable#248]
I have a specific case about following Models : Event , Comment , Attachment Each one is separate model but Comment & Attachment Belongs to Event . So is there a way to get revision history for everything related to Event directly or i need to loop on each model to bring those data together like the following

```
$event = Event::find($id);

//Get Event History
$event_history = array_merge(array_merge($event_history,$event->revisionHistory()));

//Get All Comments History
foreach(event->comments() as $comment){
            $comment_history = array_merge($comment_history,$comment->revisionHistory());
}

//All Events & Related Objects History
$history = array_merge($event_history,$comment_history);
```

**Comment by rafaelcneves** [comment]
Hi @ahmedbebars 
Do you solved this? I have something like this.

**Comment by codydh** [comment]
I'd like to bump this as well, and reference #63, as this is related. This seems like a necessary feature, as often as much information is contained in models as there is in relationships amongst models.
