### ISSUE TITLE
Tracking only when $revisionCreationsEnabled is set to true

### ISSUE THREAD

**Issue by NestorAcevedo** [VentureCraft/revisionable#263]
Hi all,

I am using this package on laravel 4.2 for auditing some tables. Many of auditing is related to track all including creations (inserts) some others only for updating.

I am trying to make a new Model can be tracked only for updates but when I update my table (from web obviously) revisionable doesn't fire anything, but if I enable $revisionCreationsEnabled to true, it tracks inserted  rows.

**Comment by lloy0076** [comment]
@NestorAcevedo - forgive me for asking, but isn't that what the documentation actually says the package should do?

**Comment by NestorAcevedo** [comment]
No, $revisionCreationsEnabled as what I understand will record creation date. I have forgotten to close this issue. I have to "override" static _boot_ method on each model that I need to log.
