### ISSUE TITLE
Protect user abuse with approved revisions

### ISSUE THREAD

**Issue by MicroDroid** [VentureCraft/revisionable#274]
We should ideally have some sort of a field such as `$needsApproval` that can be set to true so that revisions are only stored/kept when a moderator or author accepts the revision.

Something like this:

- A **separate table that holds revisions**, called `unapproved_revisions` or something
- In that table, we have some sort of a timestamp or something so that we **keep track which changes came first**
- With such structure, we can do some queuing, meaning **revisions can be approved *only* after no older unapproved revisions left**, and actually, a lot of bad things can happen without queuing. With a queue we no longer have conflicts and overrides. FIFO.

I think it should be quite trivial to implement that.

**Comment by jakub-klapka** [comment]
I think, that this should be in separate package. Majority of revisionable users won't use that in my opinion. And it sounds like lot of logic and changes in data structure.

**Comment by joshbrw** [comment]
I agree with @jakub-klapka, this sounds like quite bespoke functionality that could belong in a fork. I believe the main reason behind Revisionable is to keep an entity audit log, and this new workflow doesn't really fit that requirement.

**Comment by MicroDroid** [comment]
Sounds just about right. Thus I'll create my own of revisionable so that it includes that feature
