### ISSUE TITLE
Revisionable and UUID

### ISSUE THREAD

**Issue by rafael-franca** [VentureCraft/revisionable#278]
**System**
SO: Windows Server 2012 R2
WampServer 3.0.6 (PHP: 7.0.10, Apache: 2.4.23, MySQL: 5.7.14)

Laravel version: 5.4.18
UUID (webpatser/laravel-uuid) version: 2.0.1
Revisionable version: 1.28.0

**Problem**
When I can access any page, receive this error:

`Trait method boot has not been applied, because there are collisions with other trait methods on App\User`

I think it has something to do with UUID, because it too is a trait.

**Comment by RezRazi** [comment]
Having a similar issue with the same setup.
Any tips ?

**Comment by rafael-franca** [comment]
@RezRazi No tips. The error persists. I have changed to **Laravel Auditing**. Only need change this in the migration file.

Comment this line:
```
$table->morphs('auditable');
```

Add theses lines:
```
$table->uuid('auditable_id');
$table->string('auditable_type');
```

**Comment by RezRazi** [comment]
I was able to find a fix to that issue, add this to your model that has both `UUIDS` and `Revisionable`


`    public static function boot()
    {
        parent::boot();
    }`

**Comment by stillflame** [comment]
Same setup as you @rafael-franca . Rezrazi's comment which is indicated in the docs worked for me.
