### ISSUE TITLE
How display all revisions in div from the same time?

### ISSUE THREAD

**Issue by majweb** [VentureCraft/revisionable#282]
If a have 3 revisions fields: weight,height, bmi and when I update them its create 3 reviosions in same time. How dispaly all reviosions at same time?.

example:
25.04.2017
------------
all reviosns

**Comment by joshbrw** [comment]
You could group by the `created_at` column of the revisions.

**Comment by majweb** [comment]
Could you show me how?

**Comment by astierler** [comment]
@majweb here's an example, which will group it out by date (using Eloquent) and then display the items by time:

```php
        $revisions_grouped = \Venturecraft\Revisionable\Revision::latest('id')->limit(500)->get()
            ->groupBy(function($revision) {
                return $revision->created_at->format('d.m.Y');
            });
        foreach($revisions_grouped as $date => $revisions) {
            echo '<strong>'.$date.'</strong><ul>';
            foreach($revisions as $revision) {
                echo '<li>'.$revision->created_at->format('h:i a').': modified <strong>'.$revision->key.'</strong> on '.
                    class_basename($revision->revisionable_type).' '.$revision->revisionable_id.'</li>';
            }
            echo '</ul><hr />';
        }
```

Example output:

**27.05.2017**
 - 03:55 pm: modified password on User 2

**26.05.2017**
 - 08:43 pm: modified flags on Partner 1
 - 08:43 pm: modified flags on Partner 1007
 - 08:43 pm: modified flags on Partner 5
