### ISSUE TITLE
Get ID of last created revision

### ISSUE THREAD

**Issue by molerat619** [VentureCraft/revisionable#315]
Hey there - thanks for this great module!

When I save a model, a revision is created right after that. What's the best way to get that revision's ID (or the whole revision)?

I have read in the Docs that I could use an event listener but I was wondering if there was an easier way. Like in Laravel when you create an item, you will get it returned as a result.

Another option would be to make a query using the model, it's id and the responsible user and get the latest change. That also does not seem to be the most beautiful solution.

What do you recommend?

**Comment by molerat619** [comment]
One issue that I am facing now using the event listener is that other events are fired before the `revisionable.*` and the listeners of those events make changes to models as well. That results in getting the wrong model and revisionable in the listener for the `revisionable.*`.

**Comment by jayzyaj** [comment]
Hi I used this package but it is not working on my laravel 5.5 project. Any thoughts?
