### ISSUE TITLE
Revisionable Pivot

### ISSUE THREAD

**Issue by Antonimo** [VentureCraft/revisionable#32]
maybe you can implement this like said in here:
http://forumsarchive.laravel.io/viewtopic.php?id=10935

[quote]
There is no real support for it, as there is no real pivot model.
There is though a model-like object Pivot, which you can bound a listener to, but it will fire for any pivot, not just the one you want.
It is equal to: Event::listen('eloquent.saving: Pivot', $callback).
What you could do is to test what's is the current table inside the event.

Pivot::saving(function($pivot) {
    if ($pivot->getTable() == with(new ModelA)->theRelation()->getTable()) {
        $pivot->hash = Hash::make(Str::random());
    }
});
Where ModelA is one of the models in the relation and theRelation() is the the relation method you defined which returns the belongsToMany relation object. This way you don't have to modify the table name here if it's changed.

Edit: Btw Pivot is not an aliased class, so you can access it through the namespace: \Illuminate\Database\Eloquent\Relations\Pivot

**Comment by divdax** [comment]
Any news?

**Comment by joshbrw** [comment]
Or you could use a trait that overrides the `belongsToMany()` like I've had to do

**Comment by monove** [comment]
@Antonimo can you share your manual version with us?
