### ISSUE TITLE
morphMap doesn't work with revisionable

### ISSUE THREAD

**Issue by djave-co** [VentureCraft/revisionable#324]
Thanks for a great product. I'm having an issue which I don't think is covered in the docs and may be a bug. 

My AppServiceProvider has the following in the `boot()` method:

    Relation::morphMap([
      'users' => 'App\MyApp\Models\User',
    ]);

This works great across the entire app, except for Revisionable which gives me the following error:

> Class 'users' not found

How can I make this work?

**Comment by duellsy** [comment]
closed in PR #326
