### ISSUE TITLE
adding events in eventServiceProvider causes Class hash does not exist

### ISSUE THREAD

**Issue by gemilaguinaldo** [VentureCraft/revisionable#330]
a beginner here using the package. as said in the documentation, you need to add a code to your eventServiceProvider.php but after adding it and replacing the * sign to (created, saved, deleted) (i have used created), error "Class hash does not exist".

**Comment by astierler** [comment]
@gemilaguinaldo you may want to check anything calling or listening on those events/elsewhere. There is no reference to "hash" anywhere in the code -- and only references to the Hash command are inside of tests files only.. so something else may be interfering.

Perhaps look at your stack trace or debug your application to find out where it's happening.
