### ISSUE TITLE
Disable undo in revision

### ISSUE THREAD

**Issue by jishnu2292** [VentureCraft/revisionable#332]
How can we disable the undo button in revision history?

**Comment by joris-vercammen-cali** [comment]
The easiest is probably to overwrite the blade template and remove it there.

**Comment by jishnu2292** [comment]
> The easiest is probably to overwrite the blade template and remove it there.

if composer update?

**Comment by joris-vercammen-cali** [comment]
I mean, copy the file to your own directory and overwite it from there, we're using this package with backpack and I've copied to file to `/resources/views/vendor/backpack/crud/inc` and edited it there. If there are changes to this file in the future, we just have to read the backpack logs very carefully.

**Comment by jishnu2292** [comment]
> I mean, copy the file to your own directory and overwite it from there, we're using this package with backpack and I've copied to file to `/resources/views/vendor/backpack/crud/inc` and edited it there. If there are changes to this file in the future, we just have to read the backpack logs very carefully.

Thank you. Its working....
