### ISSUE TITLE
Backpack Integration Doesn't Work

### ISSUE THREAD

**Issue by deltoss** [VentureCraft/revisionable#338]
When using this package via the Backpack [revisions](https://backpackforlaravel.com/docs/3.4/crud-operation-revisions) feature with recent versions of backpack, it'd always put "User Guest changed the...", instead of getting the correct responsible user.

![image](https://user-images.githubusercontent.com/9282390/52673680-904aa180-2f75-11e9-95b3-e56c8ea8699b.png)

From scanning through the `revisionable` source code, this problem probably stems from how backpack recently separated from the stock auth for various reasons. I.e. instead of `Auth::user()`, it now users `backpack_user()`. For more information, see [here](https://backpackforlaravel.com/docs/3.4/base-how-to#use-separate-sessions-for-admin-user-authentication).

Are there any ways to configure `revisionable` to work with recent versions of Backpack?

**Comment by ultrono** [comment]
At the moment the package would put up on the model specified within any of the following configs: `àuth.model`and `auth.providers.users.model`.

I'd be surprised if Revisionable decided to support your specific package though. 

However, on the flip side, they have supported Sentinel auth.

Failing that, you could try overriding the `userResponsible()`method.

**Comment by barter27293** [comment]
For anyone else struggling with this - I got it working by altering the `getSystemUserId()` function in the file \vendor\venturecraft\revisionable\src\Venturecraft\Revisionable\RevisionableTrait.php 

Im a bit of a noob when it comes to php... but the below seems to work:

```
    public function getSystemUserId()
    {
        try {
            return backpack_user()->id;
            } catch (\Exception $e) {
            return null;
        }
    } 
```

I hope that helps!

**Comment by alan-smith-be** [comment]
Hello,

for information : 

I've suggested this patch : 
https://github.com/VentureCraft/revisionable/pull/377

KR
