### ISSUE TITLE
Support for Laravel 5.8

### ISSUE THREAD

**Issue by poldiwa** [VentureCraft/revisionable#341]
some things dont work on laravel 5.8

> # Events
> The `fire` method (which was deprecated in Laravel 5.4) of the  `Illuminate/Events/Dispatcher` class has been removed. You should use the dispatch method instead.
> # Testing
> The `setUp` and `tearDown` methods now require a void return type:
> https://laravel.com/docs/5.8/upgrade

**Comment by ultrono** [comment]
Has this project been abandoned by the owner? Lots of PR's open and the last commit was in August 2018. If the author has abandoned it it would good to have the repo. marked as such. I gather there are a lot of people in my situation i.e. wanting to upgrade to Laravel 5.8, but are prevented from doing so by revisionable :/

**Comment by AceWT** [comment]
I would suggest https://github.com/spatie/laravel-activitylog as an alternative to revisionable.

**Comment by ultrono** [comment]
Package is confirmed as abandoned by the owner: https://github.com/VentureCraft/revisionable/pull/321#event-1763615107

**Comment by bztrn** [comment]
> some things dont work on laravel 5.8
> 
> > # Events
> > The `fire` method (which was deprecated in Laravel 5.4) of the  `Illuminate/Events/Dispatcher` class has been removed. You should use the dispatch method instead.
> > # Testing
> > The `setUp` and `tearDown` methods now require a void return type:
> > https://laravel.com/docs/5.8/upgrade

I solved it manually. I am not sure that it is right way but it works now.

Change all declarings that contain :

\Event::fire("something else...") 
-------------------to --------------------------------------------------
\Event::dispatch("something else...")

on RevisionableTrait.php
