### ISSUE TITLE
Call to undefined method Illuminate\Events\Dispatcher::fire() in Laravel 5.8

### ISSUE THREAD

**Issue by armen9494** [VentureCraft/revisionable#346]
It looks like fire method needs to be changed

https://laravel.com/docs/5.8/upgrade

deprecated and removed

Events The fire Method

*Likelihood Of Impact: Low*

The fire method of the Illuminate/Events/Dispatcher class has been removed. I think would be used dispatch method instead.
Can this be fixed by "user", or this change needs to be made in package?

**Comment by bztrn** [comment]
I solved it manually. I am not sure that it is right way but it works now.

Change all declarings that contain :

\Event::fire("something else...") 
-------------------to --------------------------------------------------
\Event::dispatch("something else...")

on RevisionableTrait.php

**Comment by ultrono** [comment]
Package is confirmed as abandoned by the owner: https://github.com/VentureCraft/revisionable/pull/321#event-1763615107

**Comment by Slivicon** [comment]
Looks like @duellsy 
 did merge PR for this https://github.com/VentureCraft/revisionable/pull/347

**Comment by duellsy** [comment]
Can confirm, I'll close off this PR
