### ISSUE TITLE
Maintained or not?

### ISSUE THREAD

**Issue by leeovery** [VentureCraft/revisionable#348]
Hey

Is this still maintained? I think a lot of people land here and are confused. 

A clear yes or no would be super helpful and appreciated. 

It’s totally understandable if time is limited etc. I appreciate you open sourcing this in the first place. 

If it’s unmaintained perhaps someone could take over? I’d considered taking a look if I decide to use the package. 

Thanks!!!!
Lee

**Comment by Slivicon** [comment]
Package is confirmed as abandoned by the owner: https://github.com/VentureCraft/revisionable/pull/321#event-1763615107

**Comment by tabacitu** [comment]
I thought so too. But there [have been updates recently](https://github.com/VentureCraft/revisionable/commits/master), even added support for Laravel 6.0. Which I was VERY glad to see.

@duellsy it would be interesting to know if you consider the project **abandoned** (no more maintenance) or **locked** / **feature-complete** (maintained, but not planning on adding any extra features).

Even if you decide to abandon it or find another maintainer - thanks A LOT for creating this package, and maintaining it for years. I know it hasn't been easy, but you've provided a lot of value to a lot of developers. Me included. So thank you!

**Comment by duellsy** [comment]
It's something that due to work commitments I'm unable to be all over, but it's also something that I come back to sporadically. I know that isn't something that fills people with confidence, so in that light, it would be great if someone wanted to help with the maintenance etc?

**Comment by tabacitu** [comment]
Good enough for me! Thanks again. 

I personally already have my plate full, I'm afraid. But I'll try to find someone to help you out, and send them here.

Cheers!
