### ISSUE TITLE
Conversion failed when converting the nvarchar value in SQL Server

### ISSUE THREAD

**Issue by parrotsoft** [VentureCraft/revisionable#350]
Hello,  I have the following error when trying to update a record, and that this register in the history.

`SQLSTATE[22018]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Conversion failed when converting the nvarchar value '08:13' to data type int. (SQL: insert into [revisions] ([created_at], [key], [new_value], [old_value], [revisionable_id], [revisionable_type], [updated_at], [user_id]) values (2019-07-18 10:02:05.000, leave_yard_time, 08:13, 08:15, 15976, Cms\\Drivers\\DriverManifest\\DriverManifest, 2019-07-18 10:02:05.000, 14), (2019-07-18 10:02:05.000, user_id, 14, 3, 15976, Cms\\Drivers\\DriverManifest\\DriverManifest, 2019-07-18 10:02:05.000, 14), (2019-07-18 10:02:05.000, schedule_detail_id, 0, , 15976, Cms\\Drivers\\DriverManifest\\DriverManifest, 2019-07-18 10:02:05.000, 14))`

**Environment**

- Windows 10 64 Bits
- Laravel 5.4.*
- php_pdo_sqlsrv_71_ts_x64.dll
- PHP 7.1.12

Can someone help me identify this problem? Thank you.

**Comment by CarterBland** [comment]
I am seeing this issue as-well, would love to see a fix for it!

**Comment by parrotsoft** [comment]
@CarterBland Hi, do you have any solution for this?

**Comment by CarterBland** [comment]
@parrotsoft Hey, I don't have any solutions for this, so I had to remove revisions for the model that was throwing the error. I'm sure I can figure it out, but I haven't had time. I'll put this in my to-dos.

**Comment by juventus18** [comment]
check your model castings and try casting `leave_yard_time` to string
