### ISSUE TITLE
Call to undefined function array_get()

### ISSUE THREAD

**Issue by mtilokani** [VentureCraft/revisionable#360]
Hi @duellsy , I just on today installed package. And I have included trait file and make use of that trait in User model, but it is giving me following error:

`Call to undefined function Venturecraft\Revisionable\array_get()`

Could you please help me.

**Comment by ethanransdellrarebird** [comment]
There is a PR open for this
https://github.com/VentureCraft/revisionable/pull/357

**Comment by mtilokani** [comment]
@ethanransdellrarebird yes, thanks, but if could be merged to master branch then would be great to update via composer.

**Comment by duellsy** [comment]
Closed in #357

**Comment by mtilokani** [comment]
Hi @duellsy @ethanransdellrarebird I have re-installed a package but I am still facing a same issue.

**Comment by duellsy** [comment]
@mtilokani If you do a `composer update` you should pull in 1.32.0 which will have these updates.
