### ISSUE TITLE
Nothing happens when I try to save instance from `Comment` model

### ISSUE THREAD

**Issue by mahmoudmohamedramadan** [VentureCraft/revisionable#400]
I was would like to work WITH this awesome package into the Laravel project WITH an `8.40` version and PHP WITH an `^8.0` version. I've installed this package successfully and migrated the table

![{6E512FF6-4247-4940-9A2E-1FCBE4DFE649}](https://user-images.githubusercontent.com/48416569/131176498-5c76d738-8667-42ef-a403-7b579f8a3cf2.png)

also, I've used the `RevisionableTrait` trait in the `\App\Models\Comment` model and when I tried to add a new comment to the post nothing happens in the database

![{8DB90833-EA45-4BBA-AE08-7C072B3EFD60}](https://user-images.githubusercontent.com/48416569/131176697-ca80191d-77b3-469a-ad8a-d6e6aa2d6b33.png)

Here I tried to add a new comment to the post BUT nothing happens

![{797645F9-ED65-48D8-AF8B-D7E9D847F9EF}](https://user-images.githubusercontent.com/48416569/131177006-0f7a31a8-d064-4263-b9d9-601c996f759e.png)

**Comment by antoniputra** [comment]
if you are talking about storing revision for recently created model.

You need to enable this:
```php
protected $revisionCreationsEnabled = true;
```

See more:

https://github.com/VentureCraft/revisionable#storing-creations

**Comment by mahmoudmohamedramadan** [comment]
@antoniputra thanks... it's working now ✨
