### ISSUE TITLE
New Feature: Save changed and append custom data

### ISSUE THREAD

**Issue by jtomek** [VentureCraft/revisionable#418]
I need to append an entity_id to the revision records. It took me some time to figure out how to do it. 

I also noticed that others have been asking about it (https://github.com/VentureCraft/revisionable/issues/185) or even proposing PRs to append information (such as the unaccepted PR https://github.com/VentureCraft/revisionable/pull/258#issuecomment-271775300)

This is my simple yet powerful, solution:

```php
<?php

namespace App\Traits;

use Venturecraft\Revisionable\RevisionableTrait;

trait EnhancedRevisionableTrait
{
    use RevisionableTrait{
        RevisionableTrait::getAdditionalFields as originalGetAdditionalFields;
    }

    /**
     * This trait override takes the original getAdditionalFields method
     * and adds entity_id
     *
     * @return array
     */
    private function getAdditionalFields(): array
    {
        return array_merge($this->originalGetAdditionalFields(), ['entity_id' => activeEntityId()]);
    }
}

```

You will, of course, need a migration, such as:

```php

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('revisions', function (Blueprint $table) {
            $table->foreignId('entity_id')
                ->after('id')
                ->nullable()
                ->constrained()
                ->nullOnDelete();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('revisions', function (Blueprint $table) {
            $table->dropForeign(['entity_id']);
            $table->dropColumn('entity_id');
        });
    }
```

If you use this trait instead of the RevisionableTrait, you will not lose any functionality nor fall into the maintenance hell due to the surgical replacement of only a simple ```private getAdditionalFields()``` method which is easy to maintain.

I hope this might helps somebody.

**Comment by jtomek** [comment]
As it was beyond the scope of this message, I excluded it. It is a helper function I defined in the app/helpers.php.

```php
... some other code ... 

if (! function_exists('activeEntityId')) {
    function activeEntityId()
    {
        return session()->get('active_entity_id', auth()->user()?->entity_id);
    }
}
... some other code ...
```

**Comment by tombombadilll** [comment]
If the field exist on the actual model you can change this line:
`return array_merge($this->originalGetAdditionalFields(), ['entity_id' => activeEntityId()]);`
..to this..
`return array_merge($this->originalGetAdditionalFields(), ['entity_id' => $this->entity_id]);`
