### ISSUE TITLE
Unique ID of revision?

### ISSUE THREAD

**Issue by tomschlick** [VentureCraft/revisionable#49]
Is there any way to get the unique ID(s) of a revision? I'm trying to link exact changes to an existing activity feed module. I realize I could query after the update but that leaves the possibility of a race condition.

From what I've seen its not built in currently but my guess is that there would have to be some kind of "batch id" in the case of multiple fields being updated at once and that id would be set as an attribute on the model.

**Comment by Machecek** [comment]
I have created pul which i think handles what you are asing for...

https://github.com/VentureCraft/revisionable/pull/271
