### ISSUE TITLE
Use getDirty instead of trying to find dirty data manually

### ISSUE THREAD

**Issue by duellsy** [VentureCraft/revisionable#8]
Eloquent offers a method getDirty(), this can be used instead of doing the whole before / after comparison stuff

**Comment by mnfgul** [comment]
@duellsy Hi,

While making update, getDirty returns empty in my case. Details are as follow;

- I am using trait in my model
- Updating the model using;
MyModel::whereId(1)->first()->update(['field' => 'value']).
- This was not creating revisions. I digged into code and found that get  $this->dirtyData = $this->getDirty(); return empty array.

Can you help about this issue. 

Thanks.

**Comment by mnfgul** [comment]
I found my answer. The reason was that getDirty() does not return changes in case of mass updates.
- Model::update([]) does not work
- $model->attribute = 'value'; $model->save(); works.
